services:
  - type: web
    name: gamefree-browser
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
    routes:
      - path: /
        matchType: prefix
    autoDeploy: true
    disk:
      name: gamefree_storage
      mountPath: /var/data
      sizeGB: 1
